"use client";

import { AbsoluteFill, Sequence, useVideoConfig, useCurrentFrame, interpolate, Audio, Img } from "remotion";

export interface Scene {
    duration: number;
    avatar_script: string;
    subtitle: string;
    image_prompt: string;
    imageUrl?: string;
    heygenVideoUrl?: string; // Future
}

export interface VideoProps {
    title: string;
    scenes: Scene[];
}

export const MainVideo: React.FC<any> = ({ scenes, title }) => {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();

    let currentStartFrame = 0;

    return (
        <AbsoluteFill className="bg-black">
            {scenes.map((scene, index) => {
                const startFrame = currentStartFrame;
                const durationInFrames = scene.duration * fps;
                currentStartFrame += durationInFrames;

                return (
                    <Sequence key={index} from={startFrame} durationInFrames={durationInFrames}>
                        <SceneComponent scene={scene} />
                    </Sequence>
                );
            })}
        </AbsoluteFill>
    );
};

const SceneComponent: React.FC<{ scene: Scene }> = ({ scene }) => {
    const frame = useCurrentFrame();
    const { fps, width, height } = useVideoConfig();

    // Simple zoom effect for the background
    const scale = interpolate(frame, [0, scene.duration * fps], [1, 1.1]);

    return (
        <AbsoluteFill>
            {/* Background Image generated by Gemini */}
            <AbsoluteFill style={{ transform: `scale(${scale})` }}>
                {scene.imageUrl && (
                    <Img
                        src={scene.imageUrl}
                        className="w-full h-full object-cover"
                    />
                )}
            </AbsoluteFill>

            {/* Overlay for readability */}
            <AbsoluteFill className="bg-black/20" />

            {/* Subtitles (Teロップ) */}
            <div className="absolute bottom-20 left-0 right-0 flex justify-center px-20">
                <div className="bg-black/60 backdrop-blur-md border border-white/20 px-8 py-4 rounded-2xl shadow-2xl">
                    <p className="text-white text-4xl font-bold text-center tracking-tight">
                        {scene.subtitle}
                    </p>
                </div>
            </div>

            {/* Avatar Placeholder (Soon to be HeyGen) */}
            <div className="absolute bottom-0 right-0 w-1/2 h-4/5 flex items-end justify-end p-10">
                <div className="w-full h-full border-4 border-dashed border-white/20 rounded-3xl flex items-center justify-center bg-white/5 backdrop-blur-sm">
                    <p className="text-white/40 text-sm font-mono uppercase tracking-widest rotate-90">
                        [ HeyGen Avatar Placeholder ]
                    </p>
                </div>
            </div>
        </AbsoluteFill>
    );
};
