"use client";

import { AbsoluteFill, Sequence, useVideoConfig, useCurrentFrame, interpolate, Audio, Img } from "remotion";

export interface SoundEffect {
    type: "ambient" | "action" | "transition" | "emotion";
    keyword: string;
    timing: "start" | "middle" | "end" | "throughout";
    volume: number;
    url?: string;
}

export interface Scene {
    duration: number;
    avatar_script: string;
    subtitle: string;
    image_prompt: string;
    imageUrl?: string;
    audioUrl?: string;
    heygenVideoUrl?: string;
    sound_effects?: SoundEffect[];
}

export interface BGMConfig {
    url: string;
    volume: number;
}

export interface VideoProps {
    title: string;
    scenes: Scene[];
    bgm?: BGMConfig;
}

// Volume levels for audio mixing
const VOLUME_LEVELS = {
    narration: 0.85,      // Main voice - loudest
    bgm: 0.12,            // Background music - subtle
    soundEffects: 0.20,   // Sound effects - noticeable but not overpowering
};

export const MainVideo: React.FC<VideoProps> = ({ scenes, bgm }) => {
    const { fps } = useVideoConfig();

    // Pre-calculate start frames to avoid mutation during render
    const sceneFrames = scenes.map((scene, index) => {
        const startFrame = scenes.slice(0, index).reduce((acc, s) => acc + s.duration * fps, 0);
        const durationInFrames = scene.duration * fps;
        return { startFrame, durationInFrames };
    });

    return (
        <AbsoluteFill className="bg-black">
            {/* BGM - plays throughout entire video */}
            {bgm?.url && (
                <Audio
                    src={bgm.url}
                    volume={bgm.volume || VOLUME_LEVELS.bgm}
                    loop
                />
            )}

            {scenes.map((scene: Scene, index: number) => (
                <Sequence
                    key={index}
                    from={sceneFrames[index].startFrame}
                    durationInFrames={sceneFrames[index].durationInFrames}
                >
                    <SceneComponent scene={scene} />
                </Sequence>
            ))}
        </AbsoluteFill>
    );
};

const SceneComponent: React.FC<{ scene: Scene }> = ({ scene }) => {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();
    const totalFrames = scene.duration * fps;

    // Simple zoom effect for the background
    const scale = interpolate(frame, [0, totalFrames], [1, 1.1]);

    // Calculate sound effect start frames based on timing
    const getSoundStartFrame = (timing: string): number => {
        switch (timing) {
            case "start": return 0;
            case "middle": return Math.floor(totalFrames / 2);
            case "end": return Math.floor(totalFrames * 0.8);
            case "throughout": return 0;
            default: return 0;
        }
    };

    return (
        <AbsoluteFill>
            {/* Narration Audio - main voice */}
            {scene.audioUrl && (
                <Audio src={scene.audioUrl} volume={VOLUME_LEVELS.narration} />
            )}

            {/* Sound Effects - adjusted volume */}
            {scene.sound_effects?.map((sfx, i) => (
                sfx.url && (
                    <Sequence key={`sfx-${i}`} from={getSoundStartFrame(sfx.timing)}>
                        <Audio
                            src={sfx.url}
                            volume={Math.min(sfx.volume || 0.3, VOLUME_LEVELS.soundEffects)}
                            loop={sfx.timing === "throughout"}
                        />
                    </Sequence>
                )
            ))}

            {/* Background Image generated by Gemini */}
            <AbsoluteFill style={{ transform: `scale(${scale})` }}>
                {scene.imageUrl && (
                    <Img
                        src={scene.imageUrl}
                        className="w-full h-full object-cover"
                    />
                )}
            </AbsoluteFill>

            {/* Overlay for readability */}
            <AbsoluteFill className="bg-black/20" />

            {/* Subtitles (テロップ) */}
            <div className="absolute bottom-20 left-0 right-0 flex justify-center px-20">
                <div className="bg-black/60 backdrop-blur-md border border-white/20 px-8 py-4 rounded-2xl shadow-2xl">
                    <p className="text-white text-4xl font-bold text-center tracking-tight">
                        {scene.subtitle}
                    </p>
                </div>
            </div>
        </AbsoluteFill>
    );
};
